services:
  physical-api:
    container_name: physical-api
    image: physical-api:1.0.0
    build: .
    volumes:
      - .:/usr/src/application
    command: uvicorn app.main:app --host 0.0.0.0 --port 8020 --reload
    ports:
      - "8020:8020"
    env_file:
      - .env.dev
    depends_on:
      - temporal
    restart: unless-stopped
    networks:
      - biofin_network


  physical-db:
    container_name: physical-db
    image: postgres:16
    restart: unless-stopped
    env_file:
      - .env.dev
    ports:
      - "5434:5432"
    volumes:
      - physical_data:/var/lib/postgresql/data
    networks:
      - biofin_network


  physical-worker:
    container_name: physical-worker
    image: physical-api:1.0.0
    build: .
    volumes:
      - .:/usr/src/application
    command: python -m app.workers.temporal_worker
    env_file:
      - .env.dev
    depends_on:
      - temporal
    restart: unless-stopped
    networks:
      - biofin_network


  temporal:
    container_name: temporal
    image: temporalio/auto-setup:latest
    ports:
      - "7233:7233"
    environment:
      DB: postgres12
      DB_PORT: 5432
      POSTGRES_USER: temporal
      POSTGRES_PWD: temporal
      POSTGRES_SEEDS: temporal-postgres
      TEMPORAL_LOG_LEVEL: warn
    networks:
      - biofin_network


    depends_on:
      - temporal-postgres
    restart: unless-stopped

  temporal-postgres:
    container_name: temporal-postgres
    image: postgres:16
    environment:
      POSTGRES_DB: temporal
      POSTGRES_USER: temporal
      POSTGRES_PASSWORD: temporal
    restart: unless-stopped
    volumes:
      - temporal_pg_data:/var/lib/postgresql/data
    networks:
      - biofin_network


  temporal-ui:
    container_name: temporal-ui
    image: temporalio/ui:latest
    ports:
      - "8080:8080"
    environment:
      TEMPORAL_ADDRESS: temporal:7233
      TEMPORAL_TASK_QUEUE: case-workflow-task-queue
    depends_on:
      - temporal
    networks:
      - biofin_network


  minio:
    container_name: minio
    image: minio/minio:latest
    command: server /data --console-address ":9001"
    env_file:
      - .env.dev
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data
    networks:
      - biofin_network

volumes:
  physical_data:
  temporal_pg_data:
  minio_data:

networks:
  biofin_network:
    external: true
