"""baseline pre-location-rework schema

Revision ID: cb0df3527613
Revises: 
Create Date: 2026-09-22 10:58:34.424390

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cb0df3527613'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Ensure the application schemas exist (the app itself also does this at
    # startup via `CREATE SCHEMA IF NOT EXISTS`, but a migration run against a
    # genuinely fresh database should not depend on that having happened yet).
    op.execute("CREATE SCHEMA IF NOT EXISTS case_data")
    op.execute("CREATE SCHEMA IF NOT EXISTS workflow")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cases',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('case_type', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_by', sa.UUID(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='case_data'
    )
    op.create_index(op.f('ix_case_data_cases_created_by'), 'cases', ['created_by'], unique=False, schema='case_data')
    op.create_index(op.f('ix_case_data_cases_updated_by'), 'cases', ['updated_by'], unique=False, schema='case_data')
    op.create_table('countries',
    sa.Column('id', sa.SmallInteger(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=2), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    schema='case_data'
    )
    op.create_table('financing_types',
    sa.Column('id', sa.SmallInteger(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    schema='case_data'
    )
    op.create_table('implementation_stages',
    sa.Column('id', sa.SmallInteger(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    schema='case_data'
    )
    op.create_table('intermediaries',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('phone', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('contact_details', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='case_data'
    )
    op.create_table('intermediary_functions',
    sa.Column('id', sa.SmallInteger(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('function_category', sa.String(length=50), nullable=False),
    sa.CheckConstraint("function_category IN ('financial', 'biodiversity')", name='ck_intermediary_functions_function_category'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    schema='case_data'
    )
    op.create_table('nbs_approach_types',
    sa.Column('id', sa.SmallInteger(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    schema='case_data'
    )
    op.create_table('nbs_environment_types',
    sa.Column('id', sa.SmallInteger(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    schema='case_data'
    )
    op.create_table('nbs_intervention_types',
    sa.Column('id', sa.SmallInteger(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('intervention_type', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    schema='case_data'
    )
    op.create_table('nbs_societal_challenge_types',
    sa.Column('id', sa.SmallInteger(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    schema='case_data'
    )
    op.create_table('nbs_types',
    sa.Column('id', sa.SmallInteger(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    schema='case_data'
    )
    op.create_table('operator_specialties',
    sa.Column('id', sa.SmallInteger(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    schema='case_data'
    )
    op.create_table('use_of_proceeds',
    sa.Column('id', sa.SmallInteger(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    schema='case_data'
    )
    op.create_table('workflow_definitions',
    sa.Column('workflow_definition_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('workflow_definition_id'),
    sa.UniqueConstraint('code', 'version', name='uq_workflow_definitions_code_version'),
    schema='workflow'
    )
    op.create_table('case_access_audit_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=False),
    sa.Column('actor_user_id', sa.UUID(), nullable=False),
    sa.Column('target_user_id', sa.UUID(), nullable=False),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['case_data.cases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='case_data'
    )
    op.create_index(op.f('ix_case_data_case_access_audit_logs_actor_user_id'), 'case_access_audit_logs', ['actor_user_id'], unique=False, schema='case_data')
    op.create_index(op.f('ix_case_data_case_access_audit_logs_case_id'), 'case_access_audit_logs', ['case_id'], unique=False, schema='case_data')
    op.create_index(op.f('ix_case_data_case_access_audit_logs_target_user_id'), 'case_access_audit_logs', ['target_user_id'], unique=False, schema='case_data')
    op.create_table('case_basic_info',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('high_level_description', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['case_data.cases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('case_id', name='uq_case_basic_info_case_id'),
    schema='case_data'
    )
    op.create_table('case_documents',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=False),
    sa.Column('step_code', sa.String(length=100), nullable=False),
    sa.Column('field_name', sa.String(length=100), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('stored_filename', sa.String(length=255), nullable=False),
    sa.Column('upload_token', sa.String(length=32), nullable=False),
    sa.Column('content_type', sa.String(length=255), nullable=True),
    sa.Column('size_bytes', sa.Integer(), nullable=True),
    sa.Column('storage_provider', sa.String(length=50), nullable=False),
    sa.Column('bucket_name', sa.String(length=100), nullable=False),
    sa.Column('object_key', sa.String(length=500), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['case_data.cases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='case_data'
    )
    op.create_table('case_financials',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=False),
    sa.Column('loan_amount', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('use_of_proceeds_id', sa.SmallInteger(), nullable=False),
    sa.Column('nature_positive_percentage', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('nature_positive_percentage >= 0 AND nature_positive_percentage <= 100', name='ck_case_financials_nature_positive_percentage'),
    sa.ForeignKeyConstraint(['case_id'], ['case_data.cases.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['use_of_proceeds_id'], ['case_data.use_of_proceeds.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('case_id', name='uq_case_financials_case_id'),
    schema='case_data'
    )
    op.create_table('case_financing_types',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=False),
    sa.Column('financing_type_id', sa.SmallInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['case_data.cases.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['financing_type_id'], ['case_data.financing_types.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('case_id', 'financing_type_id', name='uq_case_financing_types_case_financing_type'),
    schema='case_data'
    )
    op.create_index(op.f('ix_case_data_case_financing_types_case_id'), 'case_financing_types', ['case_id'], unique=False, schema='case_data')
    op.create_table('case_funding_requirements',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=False),
    sa.Column('funding_amount', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('upfront_costs', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('maintenance_costs', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('direct_funding_amount', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('indirect_funding_amount', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('funding_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('\n            funding_amount IS NULL\n            OR direct_funding_amount IS NULL\n            OR indirect_funding_amount IS NULL\n            OR funding_amount = direct_funding_amount + indirect_funding_amount\n            ', name='ck_case_funding_requirements_total_matches_breakdown'),
    sa.ForeignKeyConstraint(['case_id'], ['case_data.cases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('case_id', name='uq_case_funding_requirements_case_id'),
    schema='case_data'
    )
    op.create_table('case_identifiers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=False),
    sa.Column('organic_farmer_number', sa.String(length=100), nullable=True),
    sa.Column('environment_scheme_number', sa.String(length=100), nullable=True),
    sa.Column('subsidy_reference', sa.String(length=100), nullable=True),
    sa.Column('registry_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['case_data.cases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('case_id', name='uq_case_identifiers_case_id'),
    schema='case_data'
    )
    op.create_table('case_intermediaries',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=False),
    sa.Column('intermediary_id', sa.Integer(), nullable=False),
    sa.Column('intermediary_function_id', sa.SmallInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['case_data.cases.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['intermediary_function_id'], ['case_data.intermediary_functions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['intermediary_id'], ['case_data.intermediaries.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('case_id', 'intermediary_id', 'intermediary_function_id', name='uq_case_intermediary_function'),
    schema='case_data'
    )
    op.create_index(op.f('ix_case_data_case_intermediaries_case_id'), 'case_intermediaries', ['case_id'], unique=False, schema='case_data')
    op.create_index(op.f('ix_case_data_case_intermediaries_intermediary_function_id'), 'case_intermediaries', ['intermediary_function_id'], unique=False, schema='case_data')
    op.create_index(op.f('ix_case_data_case_intermediaries_intermediary_id'), 'case_intermediaries', ['intermediary_id'], unique=False, schema='case_data')
    op.create_table('case_investment_rationales',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=False),
    sa.Column('nature_positive_benefits', sa.Text(), nullable=False),
    sa.Column('legislation_compliance', sa.Text(), nullable=True),
    sa.Column('additional_rationale', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['case_data.cases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('case_id', name='uq_case_investment_rationales_case_id'),
    schema='case_data'
    )
    op.create_table('case_locations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=False),
    sa.Column('polygon_wkt', sa.Text(), nullable=False),
    sa.Column('country_id', sa.SmallInteger(), nullable=False),
    sa.Column('region', sa.String(length=100), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['case_data.cases.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['country_id'], ['case_data.countries.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('case_id', name='uq_case_locations_case_id'),
    schema='case_data'
    )
    op.create_table('case_nature_based_solutions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=False),
    sa.Column('nbs_type_id', sa.SmallInteger(), nullable=False),
    sa.Column('implementation_stage_id', sa.SmallInteger(), nullable=True),
    sa.Column('nbs_environment_type_id', sa.SmallInteger(), nullable=True),
    sa.Column('nbs_approach_type_id', sa.SmallInteger(), nullable=True),
    sa.Column('nbs_intervention_type_id', sa.SmallInteger(), nullable=True),
    sa.Column('nbs_societal_challenge_type_id', sa.SmallInteger(), nullable=True),
    sa.Column('nbs_description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['case_data.cases.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['implementation_stage_id'], ['case_data.implementation_stages.id'], ),
    sa.ForeignKeyConstraint(['nbs_approach_type_id'], ['case_data.nbs_approach_types.id'], ),
    sa.ForeignKeyConstraint(['nbs_environment_type_id'], ['case_data.nbs_environment_types.id'], ),
    sa.ForeignKeyConstraint(['nbs_intervention_type_id'], ['case_data.nbs_intervention_types.id'], ),
    sa.ForeignKeyConstraint(['nbs_societal_challenge_type_id'], ['case_data.nbs_societal_challenge_types.id'], ),
    sa.ForeignKeyConstraint(['nbs_type_id'], ['case_data.nbs_types.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('case_id', name='uq_case_nature_based_solutions_case_id'),
    schema='case_data'
    )
    op.create_table('case_user_access',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('case_role', sa.String(length=50), nullable=False),
    sa.Column('can_view', sa.Boolean(), nullable=False),
    sa.Column('can_update', sa.Boolean(), nullable=False),
    sa.Column('can_delete', sa.Boolean(), nullable=False),
    sa.Column('can_assign_users', sa.Boolean(), nullable=False),
    sa.Column('is_owner', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("case_role IN ('borrower', 'funder', 'intermediary')", name='ck_case_user_access_case_role'),
    sa.ForeignKeyConstraint(['case_id'], ['case_data.cases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('case_id', 'user_id', name='uq_case_user_access_case_user'),
    schema='case_data'
    )
    op.create_index(op.f('ix_case_data_case_user_access_case_id'), 'case_user_access', ['case_id'], unique=False, schema='case_data')
    op.create_index(op.f('ix_case_data_case_user_access_user_id'), 'case_user_access', ['user_id'], unique=False, schema='case_data')
    op.create_table('intermediary_function_assignments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('intermediary_id', sa.Integer(), nullable=False),
    sa.Column('intermediary_function_id', sa.SmallInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['intermediary_function_id'], ['case_data.intermediary_functions.id'], ),
    sa.ForeignKeyConstraint(['intermediary_id'], ['case_data.intermediaries.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('intermediary_id', 'intermediary_function_id', name='uq_intermediary_function_assignment'),
    schema='case_data'
    )
    op.create_index(op.f('ix_case_data_intermediary_function_assignments_intermediary_id'), 'intermediary_function_assignments', ['intermediary_id'], unique=False, schema='case_data')
    op.create_table('operators',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('operator_specialty_id', sa.SmallInteger(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=100), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['case_data.cases.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['operator_specialty_id'], ['case_data.operator_specialties.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='case_data'
    )
    op.create_table('case_workflow_runs',
    sa.Column('case_workflow_run_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=False),
    sa.Column('workflow_definition_id', sa.Integer(), nullable=False),
    sa.Column('temporal_workflow_id', sa.String(length=255), nullable=False),
    sa.Column('temporal_run_id', sa.String(length=255), nullable=True),
    sa.Column('current_step', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['case_data.cases.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workflow_definition_id'], ['workflow.workflow_definitions.workflow_definition_id'], ),
    sa.PrimaryKeyConstraint('case_workflow_run_id'),
    sa.UniqueConstraint('case_id', name='uq_case_workflow_runs_case_id'),
    sa.UniqueConstraint('temporal_workflow_id'),
    schema='workflow'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('case_workflow_runs', schema='workflow')
    op.drop_table('operators', schema='case_data')
    op.drop_index(op.f('ix_case_data_intermediary_function_assignments_intermediary_id'), table_name='intermediary_function_assignments', schema='case_data')
    op.drop_table('intermediary_function_assignments', schema='case_data')
    op.drop_index(op.f('ix_case_data_case_user_access_user_id'), table_name='case_user_access', schema='case_data')
    op.drop_index(op.f('ix_case_data_case_user_access_case_id'), table_name='case_user_access', schema='case_data')
    op.drop_table('case_user_access', schema='case_data')
    op.drop_table('case_nature_based_solutions', schema='case_data')
    op.drop_table('case_locations', schema='case_data')
    op.drop_table('case_investment_rationales', schema='case_data')
    op.drop_index(op.f('ix_case_data_case_intermediaries_intermediary_id'), table_name='case_intermediaries', schema='case_data')
    op.drop_index(op.f('ix_case_data_case_intermediaries_intermediary_function_id'), table_name='case_intermediaries', schema='case_data')
    op.drop_index(op.f('ix_case_data_case_intermediaries_case_id'), table_name='case_intermediaries', schema='case_data')
    op.drop_table('case_intermediaries', schema='case_data')
    op.drop_table('case_identifiers', schema='case_data')
    op.drop_table('case_funding_requirements', schema='case_data')
    op.drop_index(op.f('ix_case_data_case_financing_types_case_id'), table_name='case_financing_types', schema='case_data')
    op.drop_table('case_financing_types', schema='case_data')
    op.drop_table('case_financials', schema='case_data')
    op.drop_table('case_documents', schema='case_data')
    op.drop_table('case_basic_info', schema='case_data')
    op.drop_index(op.f('ix_case_data_case_access_audit_logs_target_user_id'), table_name='case_access_audit_logs', schema='case_data')
    op.drop_index(op.f('ix_case_data_case_access_audit_logs_case_id'), table_name='case_access_audit_logs', schema='case_data')
    op.drop_index(op.f('ix_case_data_case_access_audit_logs_actor_user_id'), table_name='case_access_audit_logs', schema='case_data')
    op.drop_table('case_access_audit_logs', schema='case_data')
    op.drop_table('workflow_definitions', schema='workflow')
    op.drop_table('use_of_proceeds', schema='case_data')
    op.drop_table('operator_specialties', schema='case_data')
    op.drop_table('nbs_types', schema='case_data')
    op.drop_table('nbs_societal_challenge_types', schema='case_data')
    op.drop_table('nbs_intervention_types', schema='case_data')
    op.drop_table('nbs_environment_types', schema='case_data')
    op.drop_table('nbs_approach_types', schema='case_data')
    op.drop_table('intermediary_functions', schema='case_data')
    op.drop_table('intermediaries', schema='case_data')
    op.drop_table('implementation_stages', schema='case_data')
    op.drop_table('financing_types', schema='case_data')
    op.drop_table('countries', schema='case_data')
    op.drop_index(op.f('ix_case_data_cases_updated_by'), table_name='cases', schema='case_data')
    op.drop_index(op.f('ix_case_data_cases_created_by'), table_name='cases', schema='case_data')
    op.drop_table('cases', schema='case_data')
    # ### end Alembic commands ###
